Subida de función test
JJ/tdd-gdg pull request #5
Opened 2017-10-12 18:34 UTC by franfermi

2017-10-12 18:38 UTC, JJ requested changes
Los tests sólo tienen que fallar *antes* de escibir la función, no después...

2017-10-12 18:52 UTC, franfermi commented
No entiendo por qué me ha fallado en estos dos últimos intentos si he metido valores correctos, creo que es porque se me cuela una tabulación, en el editor no aparece

2017-10-12 18:53 UTC, JJ commented
Siempre es mejor que al menos ejecutes las cosas en local.

2017-10-13 05:09 UTC, JJ approved these changes

2017-10-13 05:09 UTC, merged